### ISSUE TITLE
口座の更新でStaleElementReferenceExceptionが発生する

### ISSUE THREAD

**Issue by nmoa** [nmoa/moneyforward-driver#2]
```
[I 231227 22:16:41 moneyforward_driver:52] Login succeeded.
[I 231227 22:16:44 moneyforward_driver:124] Updating account... [1/7]
[I 231227 22:16:44 moneyforward_driver:124] Updating account... [2/7]
[I 231227 22:16:45 moneyforward_driver:124] Updating account... [3/7]
[I 231227 22:16:46 moneyforward_driver:124] Updating account... [4/7]
[I 231227 22:16:47 moneyforward_driver:124] Updating account... [5/7]
[I 231227 22:16:48 moneyforward_driver:124] Updating account... [6/7]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/moneyforward_driver/moneyforward_driver.py", line 125, in update
    elm.click()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=92.0.4515.98); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
```

**Comment by nmoa** [comment]
更新中の状態で次のものを押そうとしているのが影響を与えているかもしれない

![image](https://github.com/nmoa/moneyforward-driver/assets/28538293/488c5781-cc25-472b-bba9-bbfe7de782ee)
